application:
  name: backend-caldera-news
  project: backend-caldera-news
  publicly_accessible: true
databases:
- type: postgresql
  version: "12"
  name: caldera_db
routers:
- name: my-router
  routes:
  - application_name: backend-caldera-news
    paths:
    - /